name: galaxy_web3
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  go_router: ^14.3.0
  gradient_borders: ^1.0.1
  sizer: ^3.0.4

dev_dependencies:
  build_runner: ^2.4.11
  copy_with_extension_gen: ^5.0.4
  flutter_test:
    sdk: flutter
  json_serializable:
  flutter_gen_runner:


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    

